rtmp {
      server {
            listen 1935;

            chunk_size 4096;

            application app {
                  live on;
                  interleave on;
                  wait_key on;
                  wait_video on;

                  allow publish all;   # OBS 송출 허용
                  allow play all; # FFmpeg의 읽기 허용
                  exec_push /usr/local/bin/ffmpeg_dash.sh $name;
            }
      }
}
